.TH BITCOINFLASH-CLI "1" "June 2016" "bitcoinflash-cli 0.12"
.SH NAME
bitcoinflash-cli \- a remote procedure call client for Bitcoin Flash.
.SH SYNOPSIS
bitcoinflash-cli [options] <command> [params] \- Send command to Bitcoin Flash.
.TP
bitcoinflash-cli [options] help \- Asks Bitcoin Flash for a list of supported commands.
.SH DESCRIPTION
This manual page documents the bitcoinflash-cli program. bitcoinflash-cli is an RPC client used to send commands to Bitcoin Flash.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBbitcoinflashd\fP, \fBbitcoinflash.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
